server:
  port: 5300
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jss_db_user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect