server:
  port: 5302

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jss_db_user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: JOBSEEKER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${random.uuid} 