server:
  port: 5500
  
spring:
  application:
    name: API-GATEWAY
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/jss/user/**
      - id: JOBSEEKER-SERVICE
        uri: lb://JOBSEEKER-SERVICE
        predicates:
          - Path=/jss/jobseeker/**
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/jss/employee/**
          
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
      
                   

    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}  
    
    